CREATE TABLE links (
    id INT AUTO_INCREMENT PRIMARY KEY,
    original_url TEXT NOT NULL,
    short_url VARCHAR(255) NOT NULL,
    delay INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- CONTA

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE links ADD COLUMN user_id INT;
ALTER TABLE links ADD COLUMN clicks INT DEFAULT 0;
ALTER TABLE links ADD FOREIGN KEY (user_id) REFERENCES users(id);

-- MODIFICACAO DE TELA DE ESPERA

CREATE TABLE waiting_templates (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    content JSON NOT NULL,
    is_preset BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

ALTER TABLE links ADD COLUMN template_id INT;
ALTER TABLE links ADD FOREIGN KEY (template_id) REFERENCES waiting_templates(id);