CREATE TABLE links (
    id INT AUTO_INCREMENT PRIMARY KEY,
    original_url TEXT NOT NULL,
    short_url VARCHAR(255) NOT NULL,
    delay INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);